version: '3.8'

services:
  tornado:
    build:
      context: .
      target: tornado
    command: python main.py
    volumes:
      - backend:/backend
    depends_on:
      - postgres
    networks:
      - default
    env_file:
      - .env

  postgres:
      image: postgres:latest
      restart: always
      volumes:
        - postgres:/var/lib/postgresql/data
        - archive:/var/lib/postgresql/archive
      networks:
        - default
      env_file:
        - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - tornado
      - postgres

volumes:
  postgres:
  backend:
  archive:
